module.exports = {
	declaration: { attributes: { version: '1.0', encoding: 'UTF-8', standalone: 'yes' } },
	elements: [
		{
			type: 'element',
			name: 'Types',
			attributes: { xmlns: 'http://schemas.openxmlformats.org/package/2006/content-types' },
			elements: [
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slideLayouts/slideLayout7.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slideLayouts/slideLayout8.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slideMasters/slideMaster1.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/presProps.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.presProps+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slideLayouts/slideLayout4.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slideLayouts/slideLayout5.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slideLayouts/slideLayout6.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slides/slide1.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slide+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slides/slide2.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slide+xml' },
					elements: [],
				},
				{ type: 'element', name: 'Override', attributes: { PartName: '/ppt/theme/theme1.xml', ContentType: 'application/vnd.openxmlformats-officedocument.theme+xml' }, elements: [] },
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slideLayouts/slideLayout2.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slideLayouts/slideLayout3.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml' },
					elements: [],
				},
				{ type: 'element', name: 'Default', attributes: { Extension: 'jpeg', ContentType: 'image/jpeg' }, elements: [] },
				{ type: 'element', name: 'Default', attributes: { Extension: 'rels', ContentType: 'application/vnd.openxmlformats-package.relationships+xml' }, elements: [] },
				{ type: 'element', name: 'Default', attributes: { Extension: 'xml', ContentType: 'application/xml' }, elements: [] },
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/presentation.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slideLayouts/slideLayout1.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/docProps/app.xml', ContentType: 'application/vnd.openxmlformats-officedocument.extended-properties+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/tableStyles.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.tableStyles+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slideLayouts/slideLayout11.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slideLayouts/slideLayout10.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/viewProps.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.viewProps+xml' },
					elements: [],
				},
				{
					type: 'element',
					name: 'Override',
					attributes: { PartName: '/ppt/slideLayouts/slideLayout9.xml', ContentType: 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml' },
					elements: [],
				},
				{ type: 'element', name: 'Override', attributes: { PartName: '/docProps/core.xml', ContentType: 'application/vnd.openxmlformats-package.core-properties+xml' }, elements: [] },
			],
		},
	],
};
